# SwiftLint Configuration for WindowSwitcher

# Paths to include for linting
included:
  - Sources

# Paths to exclude from linting
excluded:
  - .build
  - .swiftpm
  - build
  - WindowSwitcher.app
  - WindowSwitcher.xcodeproj

# Disable specific rules
disabled_rules:
  - trailing_whitespace # Auto-handled by most editors
  - todo # Allow TODO comments during development
  - blanket_disable_command # Allow blanket disables for large UI files

# Opt-in rules (not enabled by default)
opt_in_rules:
  - empty_count # Use isEmpty instead of count == 0
  - explicit_init # Avoid explicit .init()
  - first_where # Use .first(where:) instead of .filter { }.first
  - sorted_first_last # Use min() or max() instead of sorted().first
  - contains_over_first_not_nil # Use contains instead of first(where:) != nil
  - contains_over_filter_count # Use contains instead of filter.count > 0
  - contains_over_filter_is_empty # Use contains instead of !filter.isEmpty
  - empty_string # Use isEmpty instead of == ""
  - multiline_arguments # Function arguments should be on separate lines
  - multiline_parameters # Function parameters should be on separate lines
  - operator_usage_whitespace # Operators should be surrounded by whitespace
  - vertical_whitespace_closing_braces # Don't include vertical whitespace before closing braces
  - vertical_whitespace_opening_braces # Don't include vertical whitespace after opening braces

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 60
  error: 100

file_length:
  warning: 600
  error: 1000

type_body_length:
  warning: 400
  error: 600

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
  excluded:
    - id
    - x
    - y

# Force unwrapping should be avoided but allow for known safe cases
# (These are warnings, not errors, for pragmatic Swift code)

# Large tuple - limit tuple complexity
large_tuple:
  warning: 3
  error: 4

# Reporter type
reporter: "xcode"
